stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  image: openjdk
  script:
    - ./mvnw compile

test-job:
  stage: test
  image: openjdk
  script:
    - ./mvnw test

deploy-job:
  stage: deploy
  image: ruby:latest
  script:
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_NAME --api_key=$HEROKU_API_KEY
  only:
    refs:
      - deploy

deploy-rule-job:
  stage: deploy
  image: ruby:latest
  script:
    - echo 'fake deploy'
  rules:
    - if: '$CI_COMMIT_BRANCH == "webinar"'